### ISSUE TITLE
Docker 環境で MongoDB のパスが解決できない

### ISSUE THREAD

**Issue by showwin** [showwin/QIDB#121]
<img width="576" alt="qidb" src="https://cloud.githubusercontent.com/assets/1732016/13037443/20570bd0-d3c4-11e5-847c-4c0641171fb3.png">
<img width="576" alt="qidb" src="https://cloud.githubusercontent.com/assets/1732016/13037444/23568b58-d3c4-11e5-9068-68fee9e0c4ea.png">

**Comment by showwin** [comment]
@tomiit 
Docker 側のログを見ると `Could not resolve IP for: db:27017` と出ていて、MongoDB に接続できていないことがわかります。

### MongoDB のパス解決の流れ
`docker-compose.yml` で以下のように設定をしており、
```yaml:docker-compose.yml
qidb:
  build: ./
  command: '/app/docker/rails/start-server.sh'
  volumes:
    - ./:/app
  ports:
    - "3000:3000"
  links:
    - mongo:db              # 2. mongo を db という名前で扱えるようにする
  environment:
    - MONGODB_HOST=db      # 3. 環境変数 MONGODB_HOST の値を db にする
  volumes_from:
    - bundle
mongo:                     # 1.  MongoDB を mongo という名前で登録
  build: ./docker/mongo
```

`config/mongoid.yml` で
```
development:
  sessions:
    default:
      database: qidb_development
      hosts:
        - <%= (ENV["MONGODB_HOST"] || 'localhost') + ':27017' %>  # 環境変数 MONGODB_HOST が存在する場合には、そちらの値を使用する
```
となっており、MongoDB へのパスが解決される流れになっています。
が、今回はこちらに問題があるわけではありませんでした。

### 今回の原因と解決方法
Firefox でアクセスしているURLを見ると、`0.0.0.0:3000` にアクセスしているようですね。
これはおそらく Docker 上で立ち上がっているものではなくて、Windows 環境で `rails server` をして立ち上がっているサーバにアクセスしているのではないかと思います。 WIndows 環境には MongoDB は立ち上げていないので、MongoDB にアクセスできません、とエラーが出ているのだと思います。

#103 の書き方がわかりにくかったかもしれませんが、Docker が起動しているIPアドレスを確認してください。
```
$ docker-machine ls                                                                                                                                       t111@QIDB
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   ERRORS
dev   *        virtualbox   Running   tcp://192.168.99.100:2376
```
のように出てくると思いますので、この場合は `192.168.99.100` が Docker が動いている仮想マシンのIPアドレスです。

```
$ docker-compose ps                                                                                                                                       t111@QIDB
    Name                   Command               State            Ports
--------------------------------------------------------------------------------
qidb_bundle_1   /bin/sh                          Exit 0
qidb_mongo_1    /entrypoint.sh mongod            Up       27017/tcp
qidb_qidb_1     /app/docker/rails/start-se ...   Up       0.0.0.0:3000->3000/tcp
```
とすると、QIDB のアプリケーション `qidb_qidb_1` が( **仮想マシンの**ローカルホスト `0.0.0.0` の)3000番ポートで動いているのがわかりますので、`192.168.99.100:3000` にアクセスすると、Docker上で動いている QIDB にアクセスすることができます。
